### PR TITLE
--show-needed option

### PR DESCRIPTION
**Pull request by AaronDMarasco-VSI**
To complement the add/remove/replace options of `DT_NEEDED` entries. 

Otherwise I was doing things with `readelf` and `grep`.

I am not an ELF expert in any way, so if this was already possible with some of the other options, please advise.

### CODE REVIEW

**Comment by darealshinji** [comment]
I think this can be closed now that `--print-needed` was implemented and is part of release 0.9.

**Comment by AaronDMarasco-VSI** [comment]
Works for me. There was also a small memory leak fix 28b99d1 that might still be wanted (I haven't checked lately).

**Comment by domenkozar** [comment]
Closing as fixed. Please submit a PR for memory leak fix if still applicable.

**Comment by AaronDMarasco** [comment]
Confirmed the memory leak was fixed elsewhere sometime in the past 4+ years; looks like a lot of memory management moved to Modern C++.

**Pull request closed without merging**
