### PR TITLE
Skip empty section (fixes #66)

### LINKED ISSUE #66: patchelf --set-interpreter fails with `cannot find section `
I have a binary compiled with the Go 1.4 compiler from `nixpkgs`, and I'd like to run it outside of a nix environment, so I'm trying to patch the interpreter.

patchelf 0.8 gives the following error: 

```
$ patchelf --set-interpreter /lib64/ld-linux-x86-64.so.2  prog
patchelf: patchelf.cc:693: void ElfFile<Elf_Ehdr, Elf_Phdr, Elf_Shdr, Elf_Addr, Elf_Off, Elf_Dyn, Elf_Sym>::rewriteSectionsExecutable() [with Elf_Ehdr = Elf64_Ehdr; Elf_Phdr = Elf64_Phdr; Elf_Shdr = Elf64_Shdr; Elf_Addr = long unsigned int; Elf_Off = long unsigned int; Elf_Dyn = Elf64_Dyn; Elf_Sym = Elf64_Sym]: Assertion `(off_t) rdi(hdr->e_shoff) >= startOffset' failed.
Aborted
```

Which I think was fixed in [pull 39](https://github.com/NixOS/patchelf/pull/39).

I built a patchelf from master @ 63296c4e18381216f740670916608f9ef159672e, and I now get a different error:

```
 ./result/bin/patchelf --set-interpreter /lib64/ld-linux-x86-64.so.2 --debug prog
patching ELF file `prog'
Kernel page size is 4096 bytes
replacing section `.interp' with size 28
this is an executable
using replaced section `.interp'
last replaced is 2
looking at section `'
replacing section `' which is in the way
looking at section `.interp'
first reserved offset/addr is 0xc00/0x400c00
first page is 0x400000
needed space is 600
clearing first 2504 bytes
cannot find section 
```

headers:

```
$ readelf -e prog
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x43dee0
  Start of program headers:          64 (bytes into file)
  Start of section headers:          568 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         9
  Size of section headers:           64 (bytes)
  Number of section headers:         33
  Section header string table index: 11

Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [ 0]                   NULL             0000000000000000  00000000
       0000000000000000  0000000000000000           0     0     0
  [ 1] .text             PROGBITS         0000000000400c00  00000c00
       000000000029d3fb  0000000000000000  AX       0     0     16
  [ 2] .plt              PROGBITS         000000000069e000  0029e000
       0000000000000170  0000000000000010  AX       0     0     4
  [ 3] .rodata           PROGBITS         000000000069f000  0029f000
       00000000001cd6c0  0000000000000000   A       0     0     32
  [ 4] .typelink         PROGBITS         000000000086c6c0  0046c6c0
       0000000000001308  0000000000000000   A       0     0     8
  [ 5] .gosymtab         PROGBITS         000000000086d9c8  0046d9c8
       0000000000000000  0000000000000000   A       0     0     1
  [ 6] .gopclntab        PROGBITS         000000000086d9e0  0046d9e0
       00000000000f879d  0000000000000000   A       0     0     32
  [ 7] .rela             RELA             0000000000966180  00566180
       0000000000000018  0000000000000018   A      14     0     8
  [ 8] .gnu.version      VERSYM           00000000009661a0  005661a0
       0000000000000038  0000000000000002   A      14     0     2
  [ 9] .gnu.version_r    VERNEED          00000000009661e0  005661e0
       0000000000000040  0000000000000000   A      12     2     8
  [10] .hash             HASH             0000000000966220  00566220
       0000000000000090  0000000000000004   A      14     0     8
  [11] .shstrtab         STRTAB           0000000000000000  005662c0
       0000000000000185  0000000000000000           0     0     1
  [12] .dynstr           STRTAB           0000000000966460  00566460
       0000000000000189  0000000000000000   A       0     0     1
  [13] .rela.plt         RELA             0000000000966600  00566600
       0000000000000210  0000000000000018   A      14     2     8
  [14] .dynsym           DYNSYM           0000000000966820  00566820
       00000000000002a0  0000000000000018   A      12     0     8
  [15] .got              PROGBITS         0000000000967000  00567000
       0000000000000008  0000000000000008  WA       0     0     8
  [16] .got.plt          PROGBITS         0000000000967020  00567020
       00000000000000c8  0000000000000008  WA       0     0     8
  [17] .dynamic          DYNAMIC          0000000000967100  00567100
       0000000000000130  0000000000000010  WA      12     0     8
  [18] .noptrdata        PROGBITS         0000000000967240  00567240
       0000000000015eac  0000000000000000  WA       0     0     32
  [19] .data             PROGBITS         000000000097d100  0057d100
       0000000000006f90  0000000000000000  WA       0     0     32
  [20] .bss              NOBITS           00000000009840a0  005840a0
       0000000000009520  0000000000000000  WA       0     0     32
  [21] .noptrbss         NOBITS           000000000098d5c0  0058d5c0
       0000000000013448  0000000000000000  WA       0     0     32
  [22] .interp           PROGBITS         0000000000400bb0  00000bb0
       0000000000000050  0000000000000000   A       0     0     1
  [23] .symtab           SYMTAB           0000000000000000  00585000
       00000000000340f8  0000000000000018          24   195     8
  [24] .strtab           STRTAB           0000000000000000  005b90f8
       0000000000044f9a  0000000000000000           0     0     1
  [25] .tbss             NOBITS           0000000000000000  00000000
       0000000000000010  0000000000000000 WAT       0     0     8
  [26] .debug_abbrev     PROGBITS         0000000000000000  005fe092
       00000000000000fd  0000000000000000           0     0     1
  [27] .debug_line       PROGBITS         0000000000000000  005fe18f
       00000000000386b7  0000000000000000           0     0     1
  [28] .debug_frame      PROGBITS         0000000000000000  00636846
       00000000000409a4  0000000000000000           0     0     1
  [29] .debug_info       PROGBITS         0000000000000000  006771ea
       000000000010c120  0000000000000000           0     0     1
  [30] .debug_pubnames   PROGBITS         0000000000000000  0078330a
       000000000004cf2d  0000000000000000           0     0     1
  [31] .debug_pubtypes   PROGBITS         0000000000000000  007d0237
       000000000001d88b  0000000000000000           0     0     1
  [32] .debug_aranges    PROGBITS         0000000000000000  007edac2
       0000000000000030  0000000000000000           0     0     1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), l (large)
  I (info), L (link order), G (group), T (TLS), E (exclude), x (unknown)
  O (extra OS processing required) o (OS specific), p (processor specific)

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000000040 0x0000000000400040 0x0000000000400040
                 0x00000000000001f8 0x00000000000001f8  R      1000
  INTERP         0x0000000000000bb0 0x0000000000400bb0 0x0000000000400bb0
                 0x0000000000000050 0x0000000000000050  R      1
      [Requesting program interpreter: /nix/store/q0m70q5wg21hxrixkp1xk4x95sfs2fln-glibc-2.21/lib/ld-linux-x86-64.so.2]
  LOAD           0x0000000000000040 0x0000000000400040 0x0000000000400040
                 0x000000000029e130 0x000000000029e130  R E    1000
  LOAD           0x000000000029f000 0x000000000069f000 0x000000000069f000
                 0x00000000002c7ac0 0x00000000002c7ac0  R      1000
  LOAD           0x0000000000567000 0x0000000000967000 0x0000000000967000
                 0x000000000001d0a0 0x0000000000039a08  RW     1000
  DYNAMIC        0x0000000000567100 0x0000000000967100 0x0000000000967100
                 0x0000000000000130 0x0000000000000130  RW     8
  TLS            0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000010  R      8
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     8
  LOOS+5041580   0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000         8

 Section to Segment mapping:
  Segment Sections...
   00
   01     .interp
   02     .text .plt .interp
   03     .rodata .typelink .gosymtab .gopclntab .rela .gnu.version .gnu.version_r .hash .shstrtab .dynstr .rela.plt .dynsym
   04     .got .got.plt .dynamic .noptrdata .data .bss .noptrbss
   05     .dynamic
   06     .tbss
   07
   08
```

### PR DESCRIPTION
**Pull request by DoomHammer**
Title says it all. More details in #66 .

### CODE REVIEW

**Comment by DoomHammer** [comment]
@edolstra, could you take a look at this?

**Comment by edolstra** [comment]
See my remark at https://github.com/NixOS/patchelf/issues/66#issuecomment-216499621.

**Comment by sjackman** [comment]
> PR #95 may fix the latter, but it's not clear to me whether skipping sections with empty names (which is not necessarily the same as an empty section) is the right thing to do.

Why do sections with empty names cause `patchelf` to fail? This PR fixes that issue.

> `cannot find section .interp`

This error is caused by running `patchelf` on a static ELF. By default a static ELF should give an error message, although the message could be more informative. An option `--ignore-static` would be helpful to reduce this error to a warning when running `patchelf` on many executables, some of which are static.

**Comment by sjackman** [comment]
This issue seems to affect primarily Go executables, whose ELF files start with an empty first section with no name.

**Comment by steveeJ** [comment]
> This issue seems to affect primarily Go executables, whose ELF files start with an empty first section with no name.

Not knowing whether or not skipping sections with empty names is correct, we could opt for skipping the first section if it matches the given example.

```
Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [ 0]                   NULL             0000000000000000  00000000
       0000000000000000  0000000000000000           0     0     0
```

This would extend the if-clause by matching all fields with the respective zero value.
@DoomHammer @edolstra is this feasible?

**Comment by DoomHammer** [comment]
Frankly I've quite forgotten what the original fuss was all about. @sjackman do you think this suggestion is feasible?

**Comment by sjackman** [comment]
Sure, yeah. If it fixes `patchelf` for Go executables, it's good enough for me.

**Comment by iMichka** [comment]
Since #149 was merged, I think this PR can be closed.

**Pull request closed without merging**
