### PR TITLE
replace language:nix

### PR DESCRIPTION
**Pull request by abathur**
Draft PR to make CI run, per request from @Mic92 :)

### CODE REVIEW

**Comment by Mic92** [comment]
The background here is that we plan to move travis ci support for nix in a separate repository.
Right now it is supported by travis upstream however this integration is not well maintained and
changes take too long to get in. Having versioned nix installer allows smoother upgrades similar to how the install-nix github action works. See also https://discourse.nixos.org/t/fate-of-travis-ci-nix-language-support/7907/12

**Comment by Mic92** [comment]
Any reason to still mark it as a draft?

**Comment by abathur** [comment]
@Mic92 No functional reason; I just moved this whole effort to the backburner for a few days to try to get resholve~~d~~ into nixpkgs before branch-off, so I haven't done any more here aside from address your comments. (I've got tabs with the rest of the nix-community repos that use travis-ci, for example, to PR when I have a little more time...)

**Comment by Mic92** [comment]
cc @domenkozar for review. We are also using this in NUR for quite some time.

**Pull request merged**
