### PR TITLE
tests/contiguous_note_sections.s: use alternate section type prefix

### LINKED ISSUE #294: v0.13 failing to build on Fedora armv7hl
Version 0.13 is failing to build in the Fedora automatic update monitoring build for the target armv7hl. It seems to build fine on the other targets. The problem is with one of the self tests (see https://kojipkgs.fedoraproject.org//work/tasks/461/73370461/build.log for more details):

```
gcc  -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS    -march=armv7-a -mfpu=vfpv3-d16 -mtune=generic-armv7-a -mabi=aapcs-linux -mfloat-abi=hard -c -o contiguous_note_sections.o contiguous_note_sections.s
contiguous_note_sections.s: Assembler messages:
contiguous_note_sections.s:5: Error: junk at end of line, first unrecognized character is `,'
contiguous_note_sections.s:15: Error: junk at end of line, first unrecognized character is `,'
```

I'm not that familiar with using the assembler but I assume it's something to do with the `@note` following
```
.section ".note.my-section0", "a", @note
```

Looking at the GNU as manual, this seems ok to me, so it's unclear why this should be a problem. I don't have access to an armv7hl machine, so I thought I would file this in case someone knows anything before trying to make a VM.

### PR DESCRIPTION
**Pull request by ius**
Fixes #294

Testcase `contiguous_note_sections.sh` passes cross compiled on `armv7l-hf-multiplatform`, should ideally be verified on native ARMv6/7.

cc @jeremysanders @ovpanait

### CODE REVIEW

**Comment by ovpanait** [comment]
I couldn't find any documentation indicating that "%note" syntax is valid on architectures other than arm. The GNU assembler manual (https://sourceware.org/binutils/docs-2.37/as.html) only states:

```
The optional type argument may contain one of the following constants: 

...

@note

    section contains data which is used by things other than the program 

...

Note on targets where the @ character is the start of a comment (eg ARM) then another character is used instead. For example the ARM port uses the % character. 
```

However, upon testing it seems that "%note" does compile successfully with gcc on some architectures I had access to (mips, x86_64, arm, powerpc). Not sure about toolchains other than gcc.

**Comment by ius** [comment]
> I couldn't find any documentation indicating that "%note" syntax is valid on architectures other than arm.

You're right, it's undocumented. Source indicates it's fine though (see my last comment on #294).

> Not sure about toolchains other than gcc.

Fair point. I suppose this might not work for LLVM toolchains?

**Comment by Mic92** [comment]
A quick test shows that llvm's assembler does not even parse the comment of the file.

```
[nix-shell:~/git/patchelf]$ llvm-as contiguous_note_sections.s
llvm-as: contiguous_note_sections.s:1:1: error: expected top-level entity
/*
^
```

I think it's fair to say that we only support binutils's gas here since llvm asm is not compatible with gas in many ways.

**Review by Mic92 — APPROVED** [review]
Looks good to me @domenkozar  please merge.

**Pull request merged**
